name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - test
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: nx build web --configuration=development
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SANGUCHERA_SHOP }}'
          channelId: live
          projectId: sanguchera-shop
          entryPoint: dist/apps/web
