name: Deploy Dev Api
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: yarn nx build api --configuration=development
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: '${{ secrets.FIREBASE_CI_TOKEN_SANGUCHERA_SHOP }}'